package types

// Pokemon represents a Pokémon from the API
type Pokemon struct {
	ID             int      `json:"id"`
	Name           string   `json:"name"`
	BaseExperience int      `json:"base_experience"`
	Height         int      `json:"height"`
	Weight         int      `json:"weight"`
	Types          []Type   `json:"types"`
	Stats          []Stat   `json:"stats"`
	Abilities      []Ability `json:"abilities"`
	Sprites        Sprites  `json:"sprites"`
}

// Type represents the type of a Pokémon
type Type struct {
	Slot int  `json:"slot"`
	Type struct {
		Name string `json:"name"`
		URL  string `json:"url"`
	} `json:"type"`
}

// Stat represents a stat of a Pokémon
type Stat struct {
	BaseStat  int `json:"base_stat"`
	Effort    int `json:"effort"`
	Stat struct {
		Name string `json:"name"`
		URL  string `json:"url"`
	} `json:"stat"`
}

// Ability represents an ability of a Pokémon
type Ability struct {
	Ability struct {
		Name string `json:"name"`
		URL  string `json:"url"`
	} `json:"ability"`
	IsHidden bool `json:"is_hidden"`
	Slot     int  `json:"slot"`
}

// Sprites represents the images of a Pokémon
type Sprites struct {
	FrontDefault     string `json:"front_default"`
	FrontShiny       string `json:"front_shiny"`
	FrontFemale      string `json:"front_female"`
	FrontShinyFemale string `json:"front_shiny_female"`
	BackDefault      string `json:"back_default"`
	BackShiny        string `json:"back_shiny"`
	BackFemale       string `json:"back_female"`
	BackShinyFemale  string `json:"back_shiny_female"`
}

// PokemonResponse represents the simplified response for the frontend
type PokemonResponse struct {
	ID          int      `json:"id"`
	Name        string   `json:"name"`
	Types       []string `json:"types"`
	Stats       Stats    `json:"stats"`
	ImageURL    string   `json:"image_url"`
	Height      int      `json:"height"`
	Weight      int      `json:"weight"`
	Abilities   []string `json:"abilities"`
}

// Stats represents the organized stats
type Stats struct {
	HP             int `json:"hp"`
	Attack         int `json:"attack"`
	Defense        int `json:"defense"`
	SpecialAttack  int `json:"special_attack"`
	SpecialDefense int `json:"special_defense"`
	Speed          int `json:"speed"`
}

// AIExplanation represents the explanation generated by the AI
type AIExplanation struct {
	Explanation string `json:"explanation"`
	GeneratedAt string `json:"generated_at"`
} 